version: '3'
services:
  people-api:
    build:
      context: people-api
    restart: always
    ports:
      - 5555:5555
    depends_on:
      - mongo
  order-api:
    build:
      context: order-api
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - mongo
  front:
    build:
      context: front
    restart: always
    ports:
      - 3000:3000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - mongo:/data/db
volumes:
  mongo:
